[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
num-bigint = "0.4.4"
num-traits = "0.2.14"
num-integer = "0.1.45"
num-modular = {version = "0.6.1", features = ["num-bigint", "num-integer", "num-traits"]}
bytes = "1.5.0"
rand = "0.8.5"
